"use client"

import React, { createContext, useContext, useEffect, useMemo, useState } from "react"

export type Language = "vi" | "en" | "zh-TW" | "zh-CN" | "ja" | "ko"

type Dictionary = Record<string, string>

type LanguageContextType = {
  language: Language
  setLanguage: (language: Language) => void
  t: (key: string, params?: Record<string, string | number>) => string
  languages: { code: Language; label: string }[]
}

const STORAGE_KEY = "owwimoney.language"

const dictionaries: Record<Language, Dictionary> = {
  vi: {
    "nav.dashboard": "Tổng quan",
    "nav.transactions": "Giao dịch",
    "nav.partners": "Đối tác",
    "nav.categories": "Danh mục",
    "nav.sixJars": "6 Hũ",
    "nav.more": "Thêm",
    "nav.activeProfile": "Profile đang dùng",
    "nav.chooseProfile": "Chọn profile",
    "nav.switchProfile": "Đổi profile",
    "nav.darkMode": "Chế độ tối",
    "nav.lightMode": "Chế độ sáng",
    "nav.logout": "Đăng xuất",
    "header.home": "Trang chủ",
    "header.currentProfile": "Profile hiện tại",
    "header.notSelected": "Chưa chọn",
    "header.thisProfile": "Profile này",
    "header.allProfiles": "Tất cả profile",
    "dashboard.title": "Tổng quan",
    "dashboard.accountBanner": "Bạn đang xem dữ liệu tổng hợp của toàn bộ account trên tất cả profile.",
    "dashboard.weeklyExpenses": "Chi tiêu theo tuần",
    "dashboard.monthlyExpenses": "Chi tiêu theo tháng",
    "dashboard.expenseAcrossProfilesWeeks": "So sánh chi tiêu của tất cả profile trong các tuần gần đây",
    "dashboard.expenseAcrossProfilesMonths": "So sánh chi tiêu của tất cả profile trong các tháng gần đây",
    "dashboard.expenseThisProfileWeeks": "So sánh chi tiêu của profile này trong các tuần gần đây",
    "dashboard.expenseThisProfileMonths": "So sánh chi tiêu của profile này trong các tháng gần đây",
    "dashboard.weekly": "Theo tuần",
    "dashboard.monthly": "Theo tháng",
    "dashboard.expenseCategories": "Danh mục chi tiêu",
    "dashboard.categoryBreakdownAll": "Cơ cấu chi tiêu theo danh mục của tất cả profile trong tháng",
    "dashboard.categoryBreakdownProfile": "Cơ cấu chi tiêu theo danh mục của profile này trong tháng",
    "auth.welcomeBack": "Chào mừng quay lại! Hãy đăng nhập vào tài khoản của bạn",
    "auth.createAccount": "Tạo tài khoản để bắt đầu",
    "auth.emailAddress": "Địa chỉ email",
    "auth.enterEmail": "Nhập email của bạn",
    "auth.password": "Mật khẩu",
    "auth.enterPassword": "Nhập mật khẩu của bạn",
    "auth.signingIn": "Đang đăng nhập...",
    "auth.signingUp": "Đang đăng ký...",
    "auth.signIn": "Đăng nhập",
    "auth.signUp": "Đăng ký",
    "auth.noAccount": "Chưa có tài khoản?",
    "auth.signUpHere": "Đăng ký tại đây",
    "auth.haveAccount": "Đã có tài khoản?",
    "auth.signInHere": "Đăng nhập tại đây",
    "auth.allRightsReserved": "© {year} OwwiMoney. Đã đăng ký bản quyền.",
    "profile.chooseTitle": "Chọn profile của bạn",
    "profile.chooseDescription": "Chọn profile bạn muốn dùng cho phiên làm việc này.",
    "profile.listTitle": "Profiles",
    "profile.default": "Mặc định",
    "profile.opening": "Đang mở profile...",
    "profile.label": "Profile",
    "profile.create": "Tạo profile",
    "profile.createHint": "Tối đa {max} profile cho mỗi account",
    "profile.enterName": "Nhập tên profile",
    "profile.createAction": "Tạo",
    "profile.creating": "Đang tạo...",
    "profile.cancel": "Hủy",
    "profile.save": "Lưu",
    "profile.saving": "Đang lưu...",
    "profile.deleteConfirm": "Xóa profile \"{name}\"?",
    "profile.updated": "Đã cập nhật profile.",
    "profile.deleted": "Đã xóa profile.",
    "profile.errorSelect": "Không thể chọn profile lúc này.",
    "profile.errorCreate": "Không thể tạo profile lúc này.",
    "profile.errorUpdate": "Không thể cập nhật profile lúc này.",
    "profile.errorDelete": "Không thể xóa profile lúc này.",
    "profile.errorEnterName": "Vui lòng nhập tên profile.",
    "common.language": "Ngôn ngữ",
    "lang.vi": "Tiếng Việt",
    "lang.en": "English",
    "lang.zh-TW": "繁體中文",
    "lang.zh-CN": "简体中文",
    "lang.ja": "日本語",
    "lang.ko": "한국어"
  },
  en: {
    "nav.dashboard": "Dashboard",
    "nav.transactions": "Transactions",
    "nav.partners": "Partners",
    "nav.categories": "Categories",
    "nav.sixJars": "Six Jars",
    "nav.more": "More",
    "nav.activeProfile": "Active Profile",
    "nav.chooseProfile": "Choose profile",
    "nav.switchProfile": "Switch profile",
    "nav.darkMode": "Dark Mode",
    "nav.lightMode": "Light Mode",
    "nav.logout": "Logout",
    "header.home": "Home",
    "header.currentProfile": "Current profile",
    "header.notSelected": "Not selected",
    "header.thisProfile": "This profile",
    "header.allProfiles": "All profiles",
    "dashboard.title": "Dashboard",
    "dashboard.accountBanner": "You are viewing aggregated account data across all profiles.",
    "dashboard.weeklyExpenses": "Weekly Expenses",
    "dashboard.monthlyExpenses": "Monthly Expenses",
    "dashboard.expenseAcrossProfilesWeeks": "Expense comparison across all profiles over recent weeks",
    "dashboard.expenseAcrossProfilesMonths": "Expense comparison across all profiles over recent months",
    "dashboard.expenseThisProfileWeeks": "Expense comparison for this profile over recent weeks",
    "dashboard.expenseThisProfileMonths": "Expense comparison for this profile over recent months",
    "dashboard.weekly": "Weekly",
    "dashboard.monthly": "Monthly",
    "dashboard.expenseCategories": "Expense Categories",
    "dashboard.categoryBreakdownAll": "Month outcome breakdown across all profiles",
    "dashboard.categoryBreakdownProfile": "Month outcome breakdown by category for this profile",
    "auth.welcomeBack": "Welcome back! Please sign in to your account",
    "auth.createAccount": "Create an account to get started",
    "auth.emailAddress": "Email Address",
    "auth.enterEmail": "Enter your email",
    "auth.password": "Password",
    "auth.enterPassword": "Enter your password",
    "auth.signingIn": "Signing in...",
    "auth.signingUp": "Signing up...",
    "auth.signIn": "Sign In",
    "auth.signUp": "Sign Up",
    "auth.noAccount": "Don't have an account?",
    "auth.signUpHere": "Sign up here",
    "auth.haveAccount": "Already have an account?",
    "auth.signInHere": "Sign in here",
    "auth.allRightsReserved": "© {year} OwwiMoney. All rights reserved.",
    "profile.chooseTitle": "Choose your profile",
    "profile.chooseDescription": "Select the profile you want to use for this session.",
    "profile.listTitle": "Profiles",
    "profile.default": "Default",
    "profile.opening": "Opening profile...",
    "profile.label": "Profile",
    "profile.create": "Create profile",
    "profile.createHint": "Up to {max} profiles per account",
    "profile.enterName": "Enter profile name",
    "profile.createAction": "Create",
    "profile.creating": "Creating...",
    "profile.cancel": "Cancel",
    "profile.save": "Save",
    "profile.saving": "Saving...",
    "profile.deleteConfirm": "Delete profile \"{name}\"?",
    "profile.updated": "Profile updated.",
    "profile.deleted": "Profile deleted.",
    "profile.errorSelect": "Cannot select profile right now.",
    "profile.errorCreate": "Cannot create profile right now.",
    "profile.errorUpdate": "Cannot update profile right now.",
    "profile.errorDelete": "Cannot delete profile right now.",
    "profile.errorEnterName": "Please enter profile name.",
    "common.language": "Language",
    "lang.vi": "Tiếng Việt",
    "lang.en": "English",
    "lang.zh-TW": "繁體中文",
    "lang.zh-CN": "简体中文",
    "lang.ja": "日本語",
    "lang.ko": "한국어"
  },
  "zh-TW": {
    "nav.dashboard": "儀表板",
    "nav.transactions": "交易",
    "nav.partners": "夥伴",
    "nav.categories": "分類",
    "nav.sixJars": "六罐",
    "nav.more": "更多",
    "nav.activeProfile": "目前 Profile",
    "nav.chooseProfile": "選擇 Profile",
    "nav.switchProfile": "切換 Profile",
    "nav.darkMode": "深色模式",
    "nav.lightMode": "淺色模式",
    "nav.logout": "登出",
    "header.home": "首頁",
    "header.currentProfile": "目前 Profile",
    "header.notSelected": "未選擇",
    "header.thisProfile": "此 Profile",
    "header.allProfiles": "所有 Profile",
    "dashboard.title": "儀表板",
    "dashboard.accountBanner": "你正在查看所有 Profile 的彙總帳戶資料。",
    "dashboard.weeklyExpenses": "每週支出",
    "dashboard.monthlyExpenses": "每月支出",
    "dashboard.expenseAcrossProfilesWeeks": "比較所有 Profile 最近幾週的支出",
    "dashboard.expenseAcrossProfilesMonths": "比較所有 Profile 最近幾個月的支出",
    "dashboard.expenseThisProfileWeeks": "比較此 Profile 最近幾週的支出",
    "dashboard.expenseThisProfileMonths": "比較此 Profile 最近幾個月的支出",
    "dashboard.weekly": "每週",
    "dashboard.monthly": "每月",
    "dashboard.expenseCategories": "支出分類",
    "dashboard.categoryBreakdownAll": "所有 Profile 的當月分類支出分佈",
    "dashboard.categoryBreakdownProfile": "此 Profile 的當月分類支出分佈",
    "auth.welcomeBack": "歡迎回來！請登入你的帳戶",
    "auth.createAccount": "建立帳戶以開始使用",
    "auth.emailAddress": "電子郵件地址",
    "auth.enterEmail": "輸入你的電子郵件",
    "auth.password": "密碼",
    "auth.enterPassword": "輸入你的密碼",
    "auth.signingIn": "登入中...",
    "auth.signingUp": "註冊中...",
    "auth.signIn": "登入",
    "auth.signUp": "註冊",
    "auth.noAccount": "還沒有帳戶？",
    "auth.signUpHere": "在這裡註冊",
    "auth.haveAccount": "已經有帳戶了？",
    "auth.signInHere": "在這裡登入",
    "auth.allRightsReserved": "© {year} OwwiMoney. 版權所有。",
    "profile.chooseTitle": "選擇你的 Profile",
    "profile.chooseDescription": "選擇你要在這個工作階段使用的 Profile。",
    "profile.listTitle": "Profiles",
    "profile.default": "預設",
    "profile.opening": "正在開啟 Profile...",
    "profile.label": "Profile",
    "profile.create": "建立 Profile",
    "profile.createHint": "每個帳戶最多 {max} 個 Profile",
    "profile.enterName": "輸入 Profile 名稱",
    "profile.createAction": "建立",
    "profile.creating": "建立中...",
    "profile.cancel": "取消",
    "profile.save": "儲存",
    "profile.saving": "儲存中...",
    "profile.deleteConfirm": "刪除 Profile \"{name}\"？",
    "profile.updated": "Profile 已更新。",
    "profile.deleted": "Profile 已刪除。",
    "profile.errorSelect": "目前無法選擇 Profile。",
    "profile.errorCreate": "目前無法建立 Profile。",
    "profile.errorUpdate": "目前無法更新 Profile。",
    "profile.errorDelete": "目前無法刪除 Profile。",
    "profile.errorEnterName": "請輸入 Profile 名稱。",
    "common.language": "語言",
    "lang.vi": "Tiếng Việt",
    "lang.en": "English",
    "lang.zh-TW": "繁體中文",
    "lang.zh-CN": "简体中文",
    "lang.ja": "日本語",
    "lang.ko": "한국어"
  },
  "zh-CN": {
    "nav.dashboard": "仪表盘",
    "nav.transactions": "交易",
    "nav.partners": "伙伴",
    "nav.categories": "分类",
    "nav.sixJars": "六罐",
    "nav.more": "更多",
    "nav.activeProfile": "当前 Profile",
    "nav.chooseProfile": "选择 Profile",
    "nav.switchProfile": "切换 Profile",
    "nav.darkMode": "深色模式",
    "nav.lightMode": "浅色模式",
    "nav.logout": "退出登录",
    "header.home": "首页",
    "header.currentProfile": "当前 Profile",
    "header.notSelected": "未选择",
    "header.thisProfile": "这个 Profile",
    "header.allProfiles": "所有 Profile",
    "dashboard.title": "仪表盘",
    "dashboard.accountBanner": "你正在查看所有 Profile 的聚合账户数据。",
    "dashboard.weeklyExpenses": "每周支出",
    "dashboard.monthlyExpenses": "每月支出",
    "dashboard.expenseAcrossProfilesWeeks": "对比所有 Profile 最近几周的支出",
    "dashboard.expenseAcrossProfilesMonths": "对比所有 Profile 最近几个月的支出",
    "dashboard.expenseThisProfileWeeks": "对比这个 Profile 最近几周的支出",
    "dashboard.expenseThisProfileMonths": "对比这个 Profile 最近几个月的支出",
    "dashboard.weekly": "每周",
    "dashboard.monthly": "每月",
    "dashboard.expenseCategories": "支出分类",
    "dashboard.categoryBreakdownAll": "所有 Profile 的当月分类支出分布",
    "dashboard.categoryBreakdownProfile": "这个 Profile 的当月分类支出分布",
    "auth.welcomeBack": "欢迎回来！请登录你的账户",
    "auth.createAccount": "创建账户开始使用",
    "auth.emailAddress": "电子邮箱地址",
    "auth.enterEmail": "输入你的电子邮箱",
    "auth.password": "密码",
    "auth.enterPassword": "输入你的密码",
    "auth.signingIn": "登录中...",
    "auth.signingUp": "注册中...",
    "auth.signIn": "登录",
    "auth.signUp": "注册",
    "auth.noAccount": "还没有账户？",
    "auth.signUpHere": "点这里注册",
    "auth.haveAccount": "已经有账户了？",
    "auth.signInHere": "点这里登录",
    "auth.allRightsReserved": "© {year} OwwiMoney. 版权所有。",
    "profile.chooseTitle": "选择你的 Profile",
    "profile.chooseDescription": "选择你想在本次会话中使用的 Profile。",
    "profile.listTitle": "Profiles",
    "profile.default": "默认",
    "profile.opening": "正在打开 Profile...",
    "profile.label": "Profile",
    "profile.create": "创建 Profile",
    "profile.createHint": "每个账户最多 {max} 个 Profile",
    "profile.enterName": "输入 Profile 名称",
    "profile.createAction": "创建",
    "profile.creating": "创建中...",
    "profile.cancel": "取消",
    "profile.save": "保存",
    "profile.saving": "保存中...",
    "profile.deleteConfirm": "删除 Profile \"{name}\"？",
    "profile.updated": "Profile 已更新。",
    "profile.deleted": "Profile 已删除。",
    "profile.errorSelect": "暂时无法选择 Profile。",
    "profile.errorCreate": "暂时无法创建 Profile。",
    "profile.errorUpdate": "暂时无法更新 Profile。",
    "profile.errorDelete": "暂时无法删除 Profile。",
    "profile.errorEnterName": "请输入 Profile 名称。",
    "common.language": "语言",
    "lang.vi": "Tiếng Việt",
    "lang.en": "English",
    "lang.zh-TW": "繁體中文",
    "lang.zh-CN": "简体中文",
    "lang.ja": "日本語",
    "lang.ko": "한국어"
  },
  ja: {
    "nav.dashboard": "ダッシュボード",
    "nav.transactions": "取引",
    "nav.partners": "パートナー",
    "nav.categories": "カテゴリ",
    "nav.sixJars": "6つの瓶",
    "nav.more": "その他",
    "nav.activeProfile": "現在のプロフィール",
    "nav.chooseProfile": "プロフィールを選択",
    "nav.switchProfile": "プロフィールを切り替え",
    "nav.darkMode": "ダークモード",
    "nav.lightMode": "ライトモード",
    "nav.logout": "ログアウト",
    "header.home": "ホーム",
    "header.currentProfile": "現在のプロフィール",
    "header.notSelected": "未選択",
    "header.thisProfile": "このプロフィール",
    "header.allProfiles": "すべてのプロフィール",
    "dashboard.title": "ダッシュボード",
    "dashboard.accountBanner": "すべてのプロフィールをまたいだ集計アカウントデータを表示しています。",
    "dashboard.weeklyExpenses": "週間支出",
    "dashboard.monthlyExpenses": "月間支出",
    "dashboard.expenseAcrossProfilesWeeks": "全プロフィールの直近数週間の支出比較",
    "dashboard.expenseAcrossProfilesMonths": "全プロフィールの直近数か月の支出比較",
    "dashboard.expenseThisProfileWeeks": "このプロフィールの直近数週間の支出比較",
    "dashboard.expenseThisProfileMonths": "このプロフィールの直近数か月の支出比較",
    "dashboard.weekly": "週次",
    "dashboard.monthly": "月次",
    "dashboard.expenseCategories": "支出カテゴリ",
    "dashboard.categoryBreakdownAll": "全プロフィールの月別カテゴリ支出内訳",
    "dashboard.categoryBreakdownProfile": "このプロフィールの月別カテゴリ支出内訳",
    "auth.welcomeBack": "おかえりなさい。アカウントにサインインしてください",
    "auth.createAccount": "始めるにはアカウントを作成してください",
    "auth.emailAddress": "メールアドレス",
    "auth.enterEmail": "メールアドレスを入力",
    "auth.password": "パスワード",
    "auth.enterPassword": "パスワードを入力",
    "auth.signingIn": "サインイン中...",
    "auth.signingUp": "サインアップ中...",
    "auth.signIn": "サインイン",
    "auth.signUp": "サインアップ",
    "auth.noAccount": "アカウントをお持ちではありませんか？",
    "auth.signUpHere": "こちらで登録",
    "auth.haveAccount": "すでにアカウントをお持ちですか？",
    "auth.signInHere": "こちらでサインイン",
    "auth.allRightsReserved": "© {year} OwwiMoney. 無断転載を禁じます。",
    "profile.chooseTitle": "プロフィールを選択",
    "profile.chooseDescription": "このセッションで使用するプロフィールを選択してください。",
    "profile.listTitle": "Profiles",
    "profile.default": "デフォルト",
    "profile.opening": "プロフィールを開いています...",
    "profile.label": "プロフィール",
    "profile.create": "プロフィールを作成",
    "profile.createHint": "1アカウントあたり最大 {max} 個のプロフィール",
    "profile.enterName": "プロフィール名を入力",
    "profile.createAction": "作成",
    "profile.creating": "作成中...",
    "profile.cancel": "キャンセル",
    "profile.save": "保存",
    "profile.saving": "保存中...",
    "profile.deleteConfirm": "プロフィール \"{name}\" を削除しますか？",
    "profile.updated": "プロフィールを更新しました。",
    "profile.deleted": "プロフィールを削除しました。",
    "profile.errorSelect": "現在プロフィールを選択できません。",
    "profile.errorCreate": "現在プロフィールを作成できません。",
    "profile.errorUpdate": "現在プロフィールを更新できません。",
    "profile.errorDelete": "現在プロフィールを削除できません。",
    "profile.errorEnterName": "プロフィール名を入力してください。",
    "common.language": "言語",
    "lang.vi": "Tiếng Việt",
    "lang.en": "English",
    "lang.zh-TW": "繁體中文",
    "lang.zh-CN": "简体中文",
    "lang.ja": "日本語",
    "lang.ko": "한국어"
  },
  ko: {
    "nav.dashboard": "대시보드",
    "nav.transactions": "거래",
    "nav.partners": "파트너",
    "nav.categories": "카테고리",
    "nav.sixJars": "6개 통장",
    "nav.more": "더보기",
    "nav.activeProfile": "현재 프로필",
    "nav.chooseProfile": "프로필 선택",
    "nav.switchProfile": "프로필 전환",
    "nav.darkMode": "다크 모드",
    "nav.lightMode": "라이트 모드",
    "nav.logout": "로그아웃",
    "header.home": "홈",
    "header.currentProfile": "현재 프로필",
    "header.notSelected": "선택 안 됨",
    "header.thisProfile": "이 프로필",
    "header.allProfiles": "모든 프로필",
    "dashboard.title": "대시보드",
    "dashboard.accountBanner": "모든 프로필의 집계 계정 데이터를 보고 있습니다.",
    "dashboard.weeklyExpenses": "주간 지출",
    "dashboard.monthlyExpenses": "월간 지출",
    "dashboard.expenseAcrossProfilesWeeks": "모든 프로필의 최근 몇 주 지출 비교",
    "dashboard.expenseAcrossProfilesMonths": "모든 프로필의 최근 몇 달 지출 비교",
    "dashboard.expenseThisProfileWeeks": "이 프로필의 최근 몇 주 지출 비교",
    "dashboard.expenseThisProfileMonths": "이 프로필의 최근 몇 달 지출 비교",
    "dashboard.weekly": "주간",
    "dashboard.monthly": "월간",
    "dashboard.expenseCategories": "지출 카테고리",
    "dashboard.categoryBreakdownAll": "모든 프로필의 월간 카테고리 지출 분포",
    "dashboard.categoryBreakdownProfile": "이 프로필의 월간 카테고리 지출 분포",
    "auth.welcomeBack": "다시 오신 것을 환영합니다! 계정에 로그인하세요",
    "auth.createAccount": "시작하려면 계정을 만드세요",
    "auth.emailAddress": "이메일 주소",
    "auth.enterEmail": "이메일을 입력하세요",
    "auth.password": "비밀번호",
    "auth.enterPassword": "비밀번호를 입력하세요",
    "auth.signingIn": "로그인 중...",
    "auth.signingUp": "회원가입 중...",
    "auth.signIn": "로그인",
    "auth.signUp": "회원가입",
    "auth.noAccount": "계정이 없으신가요?",
    "auth.signUpHere": "여기서 가입",
    "auth.haveAccount": "이미 계정이 있나요?",
    "auth.signInHere": "여기서 로그인",
    "auth.allRightsReserved": "© {year} OwwiMoney. 모든 권리 보유.",
    "profile.chooseTitle": "프로필 선택",
    "profile.chooseDescription": "이번 세션에 사용할 프로필을 선택하세요.",
    "profile.listTitle": "Profiles",
    "profile.default": "기본",
    "profile.opening": "프로필 여는 중...",
    "profile.label": "프로필",
    "profile.create": "프로필 만들기",
    "profile.createHint": "계정당 최대 {max}개 프로필",
    "profile.enterName": "프로필 이름 입력",
    "profile.createAction": "만들기",
    "profile.creating": "생성 중...",
    "profile.cancel": "취소",
    "profile.save": "저장",
    "profile.saving": "저장 중...",
    "profile.deleteConfirm": "\"{name}\" 프로필을 삭제할까요?",
    "profile.updated": "프로필이 업데이트되었습니다.",
    "profile.deleted": "프로필이 삭제되었습니다.",
    "profile.errorSelect": "지금은 프로필을 선택할 수 없습니다.",
    "profile.errorCreate": "지금은 프로필을 만들 수 없습니다.",
    "profile.errorUpdate": "지금은 프로필을 업데이트할 수 없습니다.",
    "profile.errorDelete": "지금은 프로필을 삭제할 수 없습니다.",
    "profile.errorEnterName": "프로필 이름을 입력하세요.",
    "common.language": "언어",
    "lang.vi": "Tiếng Việt",
    "lang.en": "English",
    "lang.zh-TW": "繁體中文",
    "lang.zh-CN": "简体中文",
    "lang.ja": "日本語",
    "lang.ko": "한국어"
  }
}

const languageOptions: { code: Language; label: string }[] = [
  { code: "vi", label: "Tiếng Việt" },
  { code: "en", label: "English" },
  { code: "zh-TW", label: "繁體中文" },
  { code: "zh-CN", label: "简体中文" },
  { code: "ja", label: "日本語" },
  { code: "ko", label: "한국어" },
]

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("vi")

  useEffect(() => {
    const stored = window.localStorage.getItem(STORAGE_KEY) as Language | null
    if (stored && dictionaries[stored]) {
      setLanguageState(stored)
      document.documentElement.lang = stored
      return
    }
    document.documentElement.lang = "vi"
  }, [])

  const setLanguage = (nextLanguage: Language) => {
    setLanguageState(nextLanguage)
    window.localStorage.setItem(STORAGE_KEY, nextLanguage)
    document.documentElement.lang = nextLanguage
  }

  const value = useMemo<LanguageContextType>(() => ({
    language,
    setLanguage,
    t: (key: string, params?: Record<string, string | number>) => {
      const template = dictionaries[language]?.[key] || dictionaries.en[key] || key
      if (!params) return template
      return Object.entries(params).reduce((acc, [paramKey, paramValue]) => {
        return acc.replaceAll(`{${paramKey}}`, String(paramValue))
      }, template)
    },
    languages: languageOptions,
  }), [language])

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider")
  }

  return context
}
